
services:
    microservice-template:
        image: ${APP_IMAGE}
        restart: unless-stopped
        ports:
            - "${HOST_HTTP_PORT:-80}:${CONTAINER_HTTP_PORT:-8000}"
        env_file:
            - ${APP_ENV_FILE}
        networks:
            - sail
        depends_on:
            - redis
            - nightwatch-agent

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    nightwatch-agent:
        image: laravelphp/nightwatch-agent:latest
        env_file:
            - ${APP_ENV_FILE}
        healthcheck:
            test: php nightwatch-status
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 5s
        restart: unless-stopped
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    sail-redis:
        driver: local

